### ISSUE TITLE
Django project turn in loop

### ISSUE THREAD

**Issue by yohan8** [mishbahr/django-responsive2#6] opened 2016-02-17 13:52 UTC
Hi,

I have a already project who work perfectly. Now I want use your application to make my project a responsive website. I installed it with sudo right (necessary). I changed my settings.py like you can see [here](http://pastebin.com/CJxV8XzQ)
But when I restart my project the application turn in loop. I can't load my home page, [here my django console](http://pastebin.com/aGvVFkZJ)

Like you can see there are a RemovedInDjango110Warning in the console so I delete the 'django.core.context_processors.request', because 'django.template.context_processors.request', is already by default in context_processors from settings.py but it change nothing.

My project is on c9.io with python3.4 and django1.9

Yohan

**Comment by mishbahr** [comment] 2016-02-17 23:59
`RemovedInDjango110Warning` warning for `'django.template.context_processors.request'` is not being thrown by `django-responsive2`. Please see documentation: https://docs.djangoproject.com/en/1.9/ref/templates/api/#subclassing-context-requestcontext

Also please make sure COOKIES are enabled in your browser to make this package work.

**Comment by mishbahr** [comment] 2016-02-18 00:08
I could not reproduce this issue with Django==1.9.2 & Python 3.4.3.

**Comment by mishbahr** [comment] 2016-02-19 09:40
@yohan8 Did you figure this out?

**Comment by yohan8** [comment] 2016-02-19 15:29
Cookies are anabled in my brower.
I don't know why but today it's work with Firefox. With chrome it's still the same problem.

I think it's linked with www.c9.io

**Comment by mishbahr** [comment] 2016-02-19 18:15
Just tried it with Chrome (v48.0.2564.109) on OSX (v10.11.12) ...works as expected.
I can't help you to debug c9.io 

Regards,
Mishbah

**Comment by mishbahr** [comment] 2016-02-27 00:30
I'm closing this for now.. as I was unable to reproduce the issue. Feel free reopen it, if you can reproduce the same issue under normal django installation.

Many thanks

**Closed as completed by mishbahr** 2016-02-27 00:30 UTC
